spring:
  datasource:
    username: root
    password: jls5221318
    url: jdbc:mysql://47.104.183.2:3300/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.183.2:8848
  application:
            name: gulimall-coupon
  #格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #自增主键
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 7000
logging:
  level:
    com.atguigu.gulimall: debug

